workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CodemagicBuild_Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.geeksolutions.pyrosfit" \
            --type IOS_APP_STORE
            --create
          keychain add-certificates 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --no-codesign \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
