workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CodemagicBuild_Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.geeksolutions.pyrosfit" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
          echo "=== REVISIÓN DE EXPORT OPTIONS ==="
          cat /Users/builder/export_options.plist
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS Archive
        script: |
          flutter build ipa --release --no-codesign
      - name: Export IPA
        script: |
          PROFILE_UUID=$(find "$HOME/Library/MobileDevice/Provisioning Profiles" -name "*.mobileprovision" -exec basename {} .mobileprovision \; | head -n 1)

          cat <<EOF > /Users/builder/custom_export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>Z7554MJ336</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.geeksolutions.pyrosfit</key>
              <string>$PROFILE_UUID</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
